meta_product_name: "Vremennyy"
meta_title: "Vremennyy - All we have is now and memories"
meta_description: "Stop the chaos of constantly creating chat groups which never get deleted."
meta_image: "cover.png" # should exist in `app/assets/images/`
